name: Lint PR Title

on:
  pull_request:
   types: [opened, synchronize, edited]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v5
      - name: "Install commitlint"
        run: go install github.com/conventionalcommit/commitlint@latest
      - name : Lint the PR title
        env:
          TITLE: ${{ github.event.pull_request.title }}
        run: echo "${TITLE}" | commitlint lint
