name: Tag Release

permissions:
  contents: write

on:
  push:
    branches:
      - 'main'

jobs:
  bump_version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: "Bump version"
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: "${{ secrets.GITHUB_TOKEN }}"
      - id: cz
        name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: "Sign"
        env:
          GPG_KEYRING_B64: "${{ secrets.GPG_KEYRING_B64 }}"
          GPG_KEY_PASSPHRASE: "${{ secrets.GPG_KEY_PASSPHRASE }}"
          GPG_KEY_NAME: "${{ vars.GPG_KEY_NAME }}"
        run: |
          echo "${GPG_KEYRING_B64}" | base64 -d > /tmp/keyring.kbx
          ./gradlew sign -Psigning.secretKeyRingFile=/tmp/keyring.kbx -Psigning.password="${GPG_KEY_PASSPHRASE}" -Psigning.keyId="${GPG_KEY_NAME}"
