name: Tag Release

permissions:
  contents: write

on:
  push:
    branches:
      - 'main'

jobs:
  bump_version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: "Bump version"
    outputs:
      version: ${{ steps.cz.outputs.version }}
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.RELEASE_APP_ID }}
          private-key: ${{ secrets.RELEASE_APP_PRIVATE_KEY }}
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}
      - id: cz
        name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
  release:
    needs: bump_version
    runs-on: ubuntu-latest
    name: "Release"
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.bump_version.outputs.version }}
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Sign
        env:
          SIGNING_KEY: "${{ secrets.GPG_KEY_ASCII }}"
          SIGNING_PASSWORD: "${{ secrets.GPG_KEY_PASSPHRASE }}"
          SIGNING_KEY_ID: "${{ vars.GPG_KEY_NAME }}"
          OSSRH_USERNAME: "${{ secrets.OSSRH_USERNAME }}"
          OSSRH_PASSWORD: "${{ secrets.OSSRH_PASSWORD }}"
        run: |
          ./gradlew sign uploadArchives
