name: Tag Release

permissions:
  contents: write

on:
  push:
    branches:
      - 'main'

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
      - name: "Pull tags"
        run: |
          git pull --tags
          git config --global user.name "Release Bot"
          git config --global user.email "dtp-releasebot@users.noreply.github.com"
      - name: "Install commitizen"
        run: pip install --user -U commitizen
      - name: "Bump version"
        run: cz bump
      - name: "Push version"
        run: git push --tags origin main
